export { always } from './always'
export { complement } from './complement'
export { compose } from './compose'
export { condition1 } from './condition1'
export { curry } from './curry'
export { curry2 } from './curry2'
export { curry3 } from './curry3'
export { dispatch } from './dispatch'
export { fnull } from './fnull'
export { isa } from './isa'
export { memoize } from './memoize'
export { not } from './not'
export { partial } from './partial'
export { partial1 } from './partial1'
export { partial2 } from './partial2'
export { ifElse, ifElseC } from './ifElse'